
                <div class="image_layer image_layer_whole">
                    <div class="mask_layer">
                        <div id="network_call_center">
                            <div class="wrapper">
                                <div class="label">CALL CENTER</div>
                                <ul>                                   
                                    <li>Tél > +33(0)235 25 80 50</li>
                                </ul>
                            </div>
                        </div>
                        <div id="network_right_bottom">
                             <label><a href="/medias/files/NAVILAND-CARGO_PdT_2013_V1.pdf"><img src="/medias/images/pdf.png"> Télécharger le plan de transport 2013</a></label>
                        </div>
                    </div>
                </div>    

<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>