    <div style="width: 350px; height: 408px; position: absolute; z-index: -999;">
        <div id="map-container1" style="width: 350px; height: 408px; margin-left: -3px; position: relative;  " >
           <object type="application/x-shockwave-flash" id="map-flash" width="350" height="407">
               <param name="movie" value="/medias/swf/map.swf" />
               <param name="quality" value="high" />
               <param name="bgcolor" value="#ffffff" />
               <param name="play" value="true" />
               <param name="loop" value="true" />
               <param name="wmode" value="opaque" />
               <param name="scale" value="showall" />
               <param name="menu" value="true" />
               <param name="devicefont" value="false" />
               <param name="salign" value="" />
               <param name="allowScriptAccess" value="sameDomain" />
           </object>
        </div>
    </div> 
    <div class="image_layer image_layer_small">
                    <div class="mask_layer">
                        <div class="border-left"></div>
                        <div class="text_layer_big">
                            <div id="text_container" class="plan_de_transport-network">
                                <div class="section left">
                                    <div class="title">PLAN DE TRANSPORT</div>
                                    <div class="form" id="transport-form">
                                        <form id="form-transport">
                                                <div class="depart">
                                                        <label>
                                                            <span class="label"><?php echo $this->translate('depart') ?></span>
                                                            <span class="field">
                                                                <select name="" style="display: none;">
                                                                    <option></option>
                                                                </select>
                                                                <div class="sbHolder">
                                                                    <a href="#" class="sbToggle"></a>
                                                                    <?php if ($this->id_leaf_origin) { ?>
                                                                        <a href="#" class="sbSelector" value="<?php echo $this->id_leaf_origin ?>"></a>
                                                                    <?php } else { ?>
                                                                        <a href="#" class="sbSelector">--Choisir la ville--</a>
                                                                    <?php } ?>
                                                                    <ul class="sbOptions" style="display: none;">
                                                                    </ul>
                                                                </div>
                                                            </span>
                                                        </label>
                                                </div>
                                                <div class="arrivee">
                                                        <label>
                                                            <span class="label"><?php echo $this->translate('Arrivée') ?></span>
                                                            <span class="field">
                                                                <select name="" id="" style="display: none;">
                                                                    <option></option>
                                                                </select>
                                                                <div class="sbHolder">
                                                                    <a href="#" class="sbToggle"></a>
                                                                    <a href="#" class="sbSelector">--Choisir la ville--</a>
                                                                    <ul class="sbOptions" style="display: none;">

                                                                    </ul>
                                                                </div>
                                                            </span>
                                                        </label>
                                                </div>
                                                <div class="submit">
                                                        <span class="label">&nbsp;</span>
                                                        <span><div id="bSubmit"><img src="/medias/images/ok.png"></div></span>
                                                </div>
                                        </form>
                                        <div id="transport_form_ajax_laoder" style="margin-left: 300px; margin-top: -35px; position: absolute; display:none;">
                                            <img src="/medias/images/ajax-loader.gif">
                                          </div>
                                         
                                        <div class="transport-form-result" style="display: none;">
                                            <div class="transport-form-result_1">
                                                <div class="closing">
                                                        <label>Closing Booking > </label>
                                                        <ul class="dot">
                                                            <li id="ClosingBookingOrigin">Depart Anvers PSA : Jour A-1 12h00</li>
                                                            <li id="ClosingBookingDestination">Depart Lyon: Jour A-1 12h00</li>
                                                        </ul>
                                                </div>
                                                <div class="closing">
                                                        <label>Closing Documentation > </label>
                                                        <ul class="dot">
                                                            <li id="ClosingDocumentationOrigin">Depart Anvers PSA : Jour A-1 12h00</li>
                                                            <li id="ClosingDocumentationDestination">Depart Lyon: Jour A-1 12h00</li>
                                                        </ul>
                                                </div>
                                                <div class="block">
                                                        <span class="bold">MAD* tous quals Anvers > </span>
                                                        <span class="normal" id="MADOrigin">Jour C par route (sauf Vendredi: MDA le Mardi)</span>
                                                </div>
                                                <div class="block">
                                                        <span class="bold">Closing tous quais Anvers > </span>
                                                        <span class="normal" id="ClosingOrigin">Jour A-1 par route</span>
                                                </div>
                                               <div class="block" >
                                                        <span class="bold">Autre Caracteristique > </span>
                                                        <span class="normal" id="">Jour A-1 par route</span>
                                                </div>
                                            </div>
                                            <div class="transport-form-result_2">
                                                <p>Ces relations representent 
                                                    <span class="bold">un gain de <span id="EnvironmentalInformation"></span> TJ </span> 
                                                    par rapport a un scenario routier
                                                </p>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div>
                                <div class="transport-form-result" style="display:none;">
                                        <div class="section right">
                                            <div class="block1" id="OutwardTripSchedule">
                                                <span class="label">Lyon VENISSIEUX > Anvers PSA T.913</span>
                                                <table>
                                                    <tr>
                                                        <th>HLR<span>*</span></th>
                                                        <th>MAD<span>*</span></th>
                                                        <th>Delai</th>
                                                    </tr>
                                                </table>
                                            </div>
                                            <div class="block1" id="WaybackTripSchedule">
                                                <div class="label">Lyon VENISSIEUX > Anvers PSA T.913</div>
                                                <table>
                                                    <tr>
                                                        <th>HLR<span>*</span> (check)</th>
                                                        <th>MAD<span>*</span></th>
                                                        <th>Delai</th>
                                                    </tr>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="section bottom">
                                             <label><span class="bold">*MAD</span> > Mise A Disposition</label>
                                             <label><span class="bold">*HLR</span> > Heure Limite de Remise</label>
                                             <label><a href="/medias/files/NAVILAND-CARGO_PdT_2013_V1.pdf"><img src="/medias/images/pdf.png"> Telecharger</a></label>
                                        </div>
                                </div>
                            </div>
                            </div>
                        </div>
                </div>   

<script src="/medias/js/simulator.js"></script>
<script type="text/javascript">

function getFlashMovieObject(movieName){
	return document.getElementById(movieName);		    	
}


function SendDataToFlashMovie(str){
	flashMovie=getFlashMovieObject("map-flash");
        flashMovie.sendTextToFlash(str); 
}

                
$(document).ready(function(){ 
	
        $('#bSubmit').click(function() { 
            $('#transport_form_ajax_laoder').show();
            var id_leaf_origin = $('#transport-form .depart .sbSelector').attr('value');
            var id_leaf_destination = $('#transport-form .arrivee .sbSelector').attr('value');

            SendDataToFlashMovie(id_leaf_origin+'-'+id_leaf_destination);

            if (id_leaf_origin && id_leaf_destination) {
                getRelationMetaData(id_leaf_origin, id_leaf_destination, $('#transport-form .depart .sbSelector').html(), $('#transport-form .arrivee .sbSelector').html());
            }
        });

});



function getRelationMetaData(id_leaf_origin, id_leaf_destination, id_leaf_origin_name, id_leaf_destination_name) {
    $.ajax({
        type: "post",
        dataType: "json",
        url: '/transport-plan/get-relation-meta-data/id_leaf_origin/' + id_leaf_origin + '/id_leaf_destination/' + id_leaf_destination,
        success: function(res) {
                $('#transport_form_ajax_laoder').hide();
                $('#OutwardTripSchedule .label').html(id_leaf_origin_name + ' > ' + id_leaf_destination_name);
                $('#WaybackTripSchedule .label').html(id_leaf_destination_name + ' > ' + id_leaf_origin_name);
                $.each(res, function(k, v) {
                    $.each(v, function(k1, v1) {
                        if (k1 === 'ClosingBookingOrigin') {
                            $('#' + k1).html('Depart ' + id_leaf_origin_name + ': Jour ' + v1);
                        }
                        if (k1 === 'ClosingBookingDestination') {
                            $('#' + k1).html('Depart ' + id_leaf_destination_name + ': Jour ' + v1);
                        }
                        if (k1 === 'ClosingDocumentationOrigin') {
                            $('#' + k1).html('Depart ' + id_leaf_origin_name + ': Jour ' + v1);
                        }
                        if (k1 === 'ClosingDocumentationDestination') {
                            $('#' + k1).html('Depart ' + id_leaf_destination_name + ': Jour ' + v1);
                        }
                        if (k1 === 'MADOrigin') {
                            $('#' + k1).html(v1);
                        }
                        if (k1 === 'ClosingOrigin') {
                            <?php if (isset($_COOKIE['locale']) && $_COOKIE['locale'] == 'en_US') { ?>
                                $('#' + k1).html(v1.wording_uk_en);
                            <?php } else { ?>
                                $('#' + k1).html(v1.wording_fr_fr);
                            <?php } ?>
                        }
                        if (k1 === 'EnvironmentalInformation') {
                            var digits = v1.co2_saving.toString().split('');
                            var content = '';
                            for (var i = 0; i < digits.length; i++) {
                                content += '<span class="big_number">' + digits[i] + '</span>';
                            }
                            $('#' + k1).html(content);
                        }
                        if (k1 === 'OutwardTripSchedule' || k1 === 'WaybackTripSchedule') {
                                getTripSchedule(k1, v1);
                        }
                    });
                });
                $('.transport-form-result').show();
        }
    });
}

function getTripSchedule(k1, v1) {
    var content = '';
    <?php if (isset($_COOKIE['locale']) && $_COOKIE['locale'] == 'en_US') { ?>
    $.each(v1, function(k2, v2) {
        var tr = '<tr>';
        $.each(v2,function(k3, v3) {
            if (k3 === 'HRL' || k3 === 'MAD')
                tr += '<td>' + getEnDay(v3.day) + ' ' + v3.hour + 'h'+v3.minute + '</td>';
            else if (k3 === 'delay')
                tr += '<td>' + v3 + '</td>';
        });
        tr+='</tr>';
        content+=tr;
    });
    <?php } else { ?>
    $.each(v1, function(k2, v2) {
        var tr = '<tr>';
        $.each(v2,function(k3, v3) {
            if (k3 === 'HRL' || k3 === 'MAD')
                tr += '<td>' + getFrDay(v3.day) + ' ' + v3.hour + 'h'+v3.minute + '</td>';
            else if (k3 === 'delay')
                tr += '<td>' + v3 + '</td>';
        });
        tr+='</tr>';
        content+=tr;
    });
    <?php } ?>
    $('#' + k1 + ' table').html('<tr><th>HLR<span>*</span></th><th>MAD<span>*</span></th><th>Delai</th></tr>' + content);
}
</script>