<div class="others">
    
    <div class="others-wrapper">
        <div class="content">
        
            <div class="main-content-title">
    代购列表
</div>
<?php if ($this->lists) { ?>

<table id="daigouTable" class="display data_table">
    
    <thead>
        <tr>
            <th width="20%">产品名字</th>
            <th width="10%">图片</th>
            <th width="10%">品牌</th>
            <th width="10%">链接</th>
            <th width="10%">价格</th>
            <th width="10%">数量</th>
            <th width="10%">购买人</th>
            <th width="10%">状态</th>
            <th width="30%">备注</th>
            <th nowrap>创建时间</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($this->lists as $row) { ?>
        <tr>
            <td><?php echo $row['name'] ?></td>
            <td><?php echo $row['has_img'] ?></td>
            <td><?php echo $row['brand'] ?></td>
            <td><?php if ($row['url']) { ?>
                <a href="<?php echo $row['url'] ?>">link</a>
            <?php } ?>
            </td>
            <td><?php echo $row['unit_price'] ?></td>
            <td><?php echo $row['quantity'] ?></td>
            <td><?php echo $row['buyer'] ?></td>
            <td><?php echo $row['status'] ?></td>
            <td><?php echo $row['note'] ?></td>
            <td nowrap><?php echo $row['create_ts'] ?></td>
        </tr>
        <?php } ?>
    </tbody>
    </table>
<?php } ?>
        </div>  <!-- end content -->
    </div>
    
    <div class="others-wrapper-left">
        <ul>
        </ul>
    </div>
</div>



<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/components/datatables/dataTables.css" />
<script src="<?php echo $this->baseUrl() ?>/public/components/datatables/dataTables.min.js"></script>


<script type="text/javascript">
$(document).ready(function(){
    $('#daigouTable').dataTable({
        "iDisplayLength": 100,
        "bAutoWidth": false
    });
});
</script>