<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="border-left"></div>
        <div class="text_layer_small">
            <div id="text_container">
                <div class="title">Offres d’emplois</div>
                    <?php if(count($this->focusRowset)>0):?>
                        <ul class="jobs">
                            <?php foreach ($this->focusRowset as $job):?>
                                <li>
                                    <div class="job_title"><?php echo $job->title;?><sapn style="float:right"><a href="mailto:ressources-humaines@naviland-cargo.com"><img src="/medias/images/btn_contact.png"></a></sapn></div>
                                    <div class="job_reference"><?php echo $job->reference;?></div>
                                    <div class="job_desc"><?php echo $job->description;?></div>
                                </li>
                            <?php endforeach;?>
                        </ul>
                    <?php endif;?>
            </div>
        </div>
    </div>
</div>
                
<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>