
                <div class="image_layer image_layer_whole">
                    <div class="mask_layer">
                        
                        <div style="width: 960px; height: 408px; z-index: 200; position: absolute; top: 0; left: 0; background-image: url(<?php echo $this->baseUrl(); ?>/medias/images/mask.png);"></div>
						<div style="position: relative; z-index: 100;">
							<object type="application/x-shockwave-flash" data="<?php echo $this->baseUrl(); ?>/medias/images/metiers/player.swf" width="960" height="410">  
								<param name="movie" value="<?php echo $this->baseUrl(); ?>/medias/images/metiers/player.swf" />
								<param name="wmode" value="transparent" />
								<param name="allowfullscreen" value="true" />
								<p><a href="http://get.adobe.com/fr/flashplayer/" target="_blank">Veuillez télécharger Adobe Flash</a></p>
							</object>
                            
                        </div>
                    </div>
                </div>   
                
