            <li class="eco">
                <div class="shadow_layer">
                <div class="wrap">
                <a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'sustainable', 'action'=>'ecocalculator'), 'default', true) ?>">
                <div class="text">
                    <div class="bigger_text"><?php echo $this->translate('eco_calculez') ?></div>
                    <div class="smaller_text"><?php echo $this->translate('votre_gain_de_co2') ?></div>
                    <div class="dropdown">
                        <label>
                            <span class="label"><?php echo $this->translate('depart') ?></span>
                            <span class="field">
                                <select name="" id="select_origins" style="display: none;">
                                    <option></option>
                                </select>
                                <div class="sbHolder">
                                    <a href="#" class="sbToggle"></a>
                                    <a href="#" class="sbSelector">--Choisir la ville--</a>
                                    <ul class="sbOptions" style="display: none;">
                                        
                                    </ul>
                                </div>
                            </span>
                        </label>
                    </div>
                </div>
                </a>
                </div>
                </div>
            </li>
            
