            <li class="metiers">
                <div class="shadow_layer">
                <div class="wrap">
                <a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'metiers', 'action'=>'index'), 'default', true) ?>">
                <div class="text">
                    <div class="bigger_text"><?php echo $this->translate('decouvrez_nos_metiers') ?></div>
                </div>
                </a>
                </div>
                </div>
            </li>