            <li class="work">
                <div class="shadow_layer">
                <div class="wrap">
                    <a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'metiers', 'action'=>'traction'), 'default', true) ?>">
                    <div class="text">
                        <div class="bigger_text"><?php echo $this->translate('profitez_de_nos_experitises') ?></div>
                        <div class="smaller_text"><?php echo $this->translate('door_to_door') ?></div>
                    </div>
                    </a>
                </div>
                </div>
            </li>