<!doctype html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>DiLin大头</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/public/images/dee-2010-04.jpg">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/docs.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/jquery-ui.css" />
    <script type="text/javascript">
        var baseUrl = '<?php echo $this->baseUrl(); ?>';
    </script>
    <script src="<?php echo $this->baseUrl() ?>/public/js/jquery-1.9.1.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/public/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/script.js"></script>
</head>

<body>

    <div id="container" align="center">
        <div class="formLoginErrors"></div>
            
            <form id="formLogin" class="form-horizontal well loginForm" enctype="multipart/form-data" action="<?php echo $this->url(array('controller' => 'login', 'action' => 'process', 'module' => 'admin'), 'default', true) ?>" method="post">
                <fieldset>
                    <legend>User Login<p>If you do not have an account, you can get one for free by <a href="#" class="btn disabled">registering</a>.</p></legend>
                    <div class="control-group">
                        <label class="control-label">Username</label>
                        <div class="controls">
                            <?php echo $this->form->username ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Password</label>
                        <div class="controls">
                            <?php echo $this->form->password ?>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type ="submit" name="submit" value="Submit" class="btn btn-primary btn-large" id="formLoginBtnSubmit">
                        <a href='javascript:history.go(-1)' class="btn btn-large">Cancel</a>
                    </div>
                </fieldset>
            </form>
   </div>
</body>
</html>

<script type="text/javascript">
$(document).ready(function(){
        //
        
});    		
</script>