<div class="dashboard">
    <div class="dashboard-wrapper">
        
        <div class="content-block">
            
            <?php if ($this->categories) { ?>

                <table class="display" id="table-name-categories">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Controller</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php foreach ($this->categories as $row) { ?>
                        <tr>
                            <td><?php echo $row['id'] ?></td>
                            <td><?php echo $row['controller'] ?></td>
                            <td><?php echo $row['name'] ?></td>
                            <td><?php echo $row['status'] ?></td>
                            <td><a href="#" class="edit-row" id="edit-row-<?php echo $row['id'] ?>">edit</a></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    </table>
            <?php } ?>
        </div>
    </div>
</div>
<div class="form-edit" style="display: none;">
    <form>
        <?php echo $this->category_form->id ?>
        <div class="block">
            <label>Controller</label>
            <div><?php echo $this->category_form->controller ?></div>
        </div>
        <div class="block">
            <label>Category</label>
            <div><?php echo $this->category_form->name ?></div>
        </div>
        <div class="block">
            <label>Status</label>
            <div><?php echo $this->category_form->status ?></div>
        </div>
    </form>
</div>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/components/datatables/dataTables.css" />
<script src="<?php echo $this->baseUrl() ?>/public/components/datatables/dataTables.min.js"></script>


<script type="text/javascript">
$(document).ready(function(){
    
    $(".edit-row").click(function(e){
        e.preventDefault();
        var id = $(this).attr('id').substr(9);
        $.ajax({
            type: "post",
            url: "/admin/ajax/get-category",
            data: { 
                id: id
            },
            success: function(response) {
                if (response.status == 1) {
                    var data = response.data;
                    $('input#id').val(data.id);
                    $('input#name').val(data.name);
                    $('input#controller').val(data.controller);
                    $('input#status').val(data.status);
                }
            }
        });
        //$('.dialog-edit-table').empty();
        $('.form-edit').dialog('open');
    });
    
    $(".form-edit" ).dialog({
        autoOpen: false,
        modal: true,
        title: 'EDIT',
        width: '400',
        buttons: {
            Cancel: function() {
                $( this ).dialog( "close" ); 
            },
            Ok: function() {
                $( this ).dialog( "close" );
            }
        }
    });
});
</script>