<div class="dashboard">
    <div class="dashboard-wrapper">
        
        <div class="content-block">
            
            <div class="content-block-title">代购</div>
            
            <?php if ($this->daigous) { ?>

                <table id="daigouTable" class="display data_table">
    
                    <thead>
                        <tr>
                            <th width="20%">产品名字</th>
                            <th width="10%">图片</th>
                            <th width="10%">品牌</th>
                            <th width="10%">链接</th>
                            <th width="10%">价格</th>
                            <th width="10%">数量</th>
                            <th width="10%">购买人</th>
                            <th width="10%">状态</th>
                            <th width="30%">备注</th>
                            <th nowrap>创建时间</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php foreach ($this->daigous as $row) { ?>
                        <tr>
                            <td><?php echo $row['name'] ?></td>
                            <td><?php echo $row['has_img'] ?></td>
                            <td><?php echo $row['brand'] ?></td>
                            <td><?php if ($row['url']) { ?>
                                <a href="<?php echo $row['url'] ?>">link</a>
                            <?php } ?>
                            </td>
                            <td><?php echo $row['unit_price'] ?></td>
                            <td><?php echo $row['quantity'] ?></td>
                            <td><?php echo $row['buyer'] ?></td>
                            <td><?php echo $row['status'] ?></td>
                            <td><?php echo $row['note'] ?></td>
                            <td nowrap><?php echo $row['create_ts'] ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            <?php } ?>
            
        </div>
    </div>
</div>
<div class="form-category" enctype="multipart/form-data" style="display: none;">
    <form>
        <?php echo $this->category_form->id ?>
        <div class="block">
            <label>Controller</label>
            <div><?php echo $this->category_form->controller ?></div>
        </div>
        <div class="block">
            <label>Category</label>
            <div><?php echo $this->category_form->name ?></div>
        </div>
        <div class="block">
            <label>Status</label>
            <div><?php echo $this->category_form->status ?></div>
        </div>
    </form>
</div>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/components/datatables/dataTables.css" />
<script src="<?php echo $this->baseUrl() ?>/public/components/datatables/dataTables.min.js"></script>


<script type="text/javascript">
$(document).ready(function(){
    
    addRow();
    
    editRow();
    
});

function addRow()
{
    $(".add-row").click(function(e) {
        e.preventDefault();
        
        form('ADD');
        $('input').val('');
        $('.form-category').dialog('open');
    });
}

function editRow()
{
    $(".edit-row").click(function(e){
        e.preventDefault();
        var id = $(this).attr('id').substr(9);
        $.ajax({
            type: "post",
            url: "/admin/ajax/get-category",
            data: { 
                id: id
            },
            success: function(response) {
                if (response.status == 1) {
                    var data = response.data;
                    $('input#id').val(data.id);
                    $('input#name').val(data.name);
                    $('input#controller').val(data.controller);
                    $('input#status').val(data.status);
                }
            }
        });
        form('EDIT');
        $('.form-category').dialog('open');
    });
}

function form(title) {
    $(".form-category" ).dialog({
        autoOpen: false,
        modal: true,
        title: title,
        width: '400',
        buttons: {
            Cancel: function() {
                $( this ).dialog( "close" ); 
            },
            Ok: function() {
                if (title === 'ADD') 
                    addCategory();
                if (title === 'EDIT')
                    editCategory();
                $( this ).dialog( "close" );
            }
        }
    });
}

function addCategory() {
    $.ajax({
        type: "post",
        url: "/admin/ajax/add-category",
        data: { 
            //data: $('.form-category form').serialize()
            controller: $('#controller').val(),
            name: $('#name').val(),
            status: $('#status').children(':selected').val()
        },
        success: function(response) {
            if (response.status == 1) {
                var id = response.data.id;
                $('table#table-categories tbody').append(
                        '<tr id="cat_' + id + '"><td>' + response.data.id + '</td><td>' + $('#controller').val() + '</td><td>' + $('#name').val() + '</td><td>' + $('#status').children(':selected').val() + '</td><td>' + '<a href="#" class="edit-row" id="edit-row-' + id + '">edit</a>' + '</td></tr>'
                );
                editRow();
            }
        }
    });
}

function editCategory() {
    var id = $('form #id').val();
    $.ajax({
        type: "post",
        url: "/admin/ajax/update-category",
        data: { 
            id: id,
            controller: $('#controller').val(),
            name: $('#name').val(),
            status: $('#status').children(':selected').val()
        },
        success: function(response) {
            if (response.status == 1) {
                $("table#table-categories tbody #cat_" + id).html(
                    '<td>' + $("form #id").val() + '</td><td>' + $('#controller').val() + '</td><td>' + $('#name').val() + '</td><td>' + $('#status').children(':selected').val() + '</td><td>' + '<a href="#" class="edit-row" id="edit-row-' + id + '">edit</a>' + '</td>'
                );
                editRow();
            }
        }
    });
}
</script>