

<div class="image_layer image_layer_big">
    <div class="mask_layer">
        <div class="text_layer_small">
            <div id="text_container" class="footer-credits">
                <div class="title">PLAN DU SITE</div>
                <div >
                    <?php echo $this->navigation()->menu()->setUlClass('sitemap_navi')->renderMenu(Zend_Registry::get('navigation_fr')); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . 'credits' ?>.jpg) no-repeat 0 center');
    var content = $('#breadcrumbs .inner').html() + 'credits';
    $('#breadcrumbs .inner').html(content);
});
</script>
