<div class="index">
    <div class="index-wrapper">
        <div class="content">
            <iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=1&noborder=1&isWeibo=1&isFans=1&uid=1890664504&verifier=6e85d973&dpc=1"></iframe>
        </div>
    
    </div>
</div>