<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/ecocalculateur/style.css">

<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/libs/JQuery.SelectBox/jquery.selectbox-0.2.min.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/libs/HighCharts-2.3.3/highcharts.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/libs/GetElementsByClassName/getElementsByClassName-1.0.1.js"></script>

<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/libs/Heritage.js"></script>

<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/CCtrlEcoCalculateur.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/CWSManager.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/CRelation.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/CCountry.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/CStation.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/CEnvironmentalData.js"></script>
<script language="Javascript" SRC="<?php echo $this->baseUrl() ?>/medias/js/libs/ecocalculateur/CGlobalReporting.js"></script>

<script language="Javascript">
	var ctrlEcoCalculateur = CCtrlEcoCalculateur.getInstance();
	CWSManager.setWSAddress("<?php echo $this->baseUrl().'/' ?>");
	
	$(document).ready(
		function()
		{
			<?php
			if ($this->hasPreselectedOriginPlateforme)
			{
				echo 'ctrlEcoCalculateur.forceOriginPlateforme('.$this->idPreselectedOriginPlateforme.');';
			}
			?>
			ctrlEcoCalculateur.initialisation();
		}
	);
</script>

<div class="image_layer image_layer_big">
    <div class="mask_layer" >
   		<div class="ecocalclateur_border_left"></div>
        <div id="ecocalculateur" >
			<div id="ecocalculateur_extratab_container" >
				<div id="ecocalculateur_extratab_calcul_01" class="ecocalculateur_extratab selected">
				</div>
				<div id="ecocalculateur_extratab_calcul_02" class="ecocalculateur_extratab up unselected hide">
				</div>
				<div id="ecocalculateur_extratab_calcul_03" class="ecocalculateur_extratab up unselected hide">
				</div>
				<div id="ecocalculateur_extratab_calcul_04" class="ecocalculateur_extratab up unselected hide">
				</div>
				<div id="ecocalculateur_extratab_global" class="ecocalculateur_extratab up unselected">
				</div>
			</div>
			<div id="ecocalculateur_tab_container">
				<ul id="ecocalculateur_tab_container_ul">
				</ul>
				<div id="ecocalculateur_input_tab">
					<div id="ecocalculateur_input_title">
						<span id="ecocalculateur_input_title_1">ÉCO<span class="sub">2</span>Calculez</span><br/>
						<span id="ecocalculateur_input_title_2">Votre gain de CO<span class="sub">2</span>
                                                <span id="ecocalculateur_input_title_3">
                                                    Naviland Cargo, c’est un gain moyen de 20% d’empreinte C02.<br/> 
                                                    Renseignez le formulaire ci-contre pour préciser une (des) relation(s).
                                                </span>
					</div>
					<div id="ecocalculateur_input_form">
						<table id="ecocalculateur_input_od_form_table">
							<tbody>
                                                                <tr>
                                                                        <td id="ecocalculateur_input_origin_label"><?php echo $this->translate('Départ') ?></td>
                                                                </tr>
								<tr>
									<td id="ecocalculateur_input_origin_country_label" class="ecocalclateur_input_field_label">Pays</td>
									<td id="ecocalculateur_input_origin_zip_label" class="ecocalclateur_input_field_label">Code postal</td>
									<td rowspan="2" id="ecocalculateur_input_origin_or"><span id="ecocalculateur_input_origin_or_text">ou</span></td>
									<td id="ecocalculateur_input_origin_plateforme_label" class="ecocalclateur_input_field_label">Plateforme</td>
								</tr>
								<tr class="ecocalculateur_input_end_section">
									<td id="ecocalculateur_input_origin_country">
										<select id="ecocalculateur_input_origin_country_component">
										</select>
									</td>
									<td id="ecocalculateur_input_origin_zip">
										<input id="ecocalculateur_input_origin_zip_component" type="text"></input>
									</td>
									<td id="ecocalculateur_input_origin_plateforme">
										<select id="ecocalculateur_input_origin_plateforme_component">
										</select>
									</td>
								</tr>
                                                                <tr>
                                                                        <td id="ecocalculateur_input_destination_label"><?php echo $this->translate('Arrivée') ?></td>
                                                                </tr>
								<tr>
									<td id="ecocalculateur_input_destination_country_label" class="ecocalclateur_input_field_label">Pays</td>
									<td id="ecocalculateur_input_destination_zip_label" class="ecocalclateur_input_field_label">Code postal</td>
									<td rowspan="2" id="ecocalculateur_input_destination_or"><span id="ecocalculateur_input_destination_or_text">ou</span></td>
									<td id="ecocalculateur_input_destination_plateforme_label" class="ecocalclateur_input_field_label">Plateforme</td>
								</tr>
								<tr>
									<td id="ecocalculateur_input_destination_country">
										<select id="ecocalculateur_input_destination_country_component">
										</select>
									</td>
									<td id="ecocalculateur_input_destination_zip">
										<input id="ecocalculateur_input_destination_zip_component" type="text"></input>
									</td>
									<td id="ecocalculateur_input_destination_plateforme">
										<select id="ecocalculateur_input_destination_plateforme_component">
										</select>
									</td>
								</tr>
							</tbody>
						</table>
						
						<table id="ecocalculateur_input_goods_form_table">
							<tbody>
								<tr>
									<td id="ecocalculateur_input_goods_20p_label" class="ecocalclateur_input_field_label ecocalclateur_input_field_goods_label">Nbre de 20'</td>
									<td id="ecocalculateur_input_goods_30p_label" class="ecocalclateur_input_field_label ecocalclateur_input_field_goods_label">Nbre de 30'</td>
									<td id="ecocalculateur_input_goods_40p_label" class="ecocalclateur_input_field_label ecocalclateur_input_field_goods_label">Nbre de 40'</td>
								</tr>
								<tr>
									<td id="ecocalculateur_input_goods_20p">
										<input id="ecocalculateur_input_goods_20p_component" class="ecocalculateur_input_goods_component" type="text"></input>
									</td>
									<td id="ecocalculateur_input_goods_30p">
										<input id="ecocalculateur_input_goods_30p_component" class="ecocalculateur_input_goods_component" type="text"></input>
									</td>
									<td id="ecocalculateur_input_goods_40p">
										<input id="ecocalculateur_input_goods_40p_component" class="ecocalculateur_input_goods_component" type="text"></input>
									</td>
								</tr>
							</tbody>
						</table>
						
						<table id="ecocalculateur_input_trip_form_table">
							<tbody>
								<tr>
									<td>
										<input type="checkbox" id="ecocalculateur_input_trip_empty_component" class="ecocalculateur_input_trip_component"><span class="ecocalclateur_input_field_label">Vide</span></input>
									</td>
									<td>
										<input type="checkbox" id="ecocalculateur_input_trip_wayback_component" class="ecocalculateur_input_trip_component"><span class="ecocalclateur_input_field_label">A/R</span></input>
									</td>
									<td>
										<div id="ecocalculateur_input_calculate_button"></div>
									</td>
                                                                        <td>
                                                                                <div id="ecocalculateur_input_calculate_button_ajax_loader" style="display:none;">
                                                                                    <img src="/medias/images/ajax-loader.gif">
                                                                                  </div>
                                                                        </td>
								</tr>
							</tbody>
						</table>
					</div>
					
					<div id="ecocalculateur_relation_result_chart">
						<div id="ecocalculateur_relation_result_chart_chart_container">
							<div id="ecocalculateur_relation_result_chart_chart_container_uti" class="ecocalculateur_relation_result_chart"></div>
							<div id="ecocalculateur_relation_result_chart_chart_container_global" class="ecocalculateur_relation_result_chart"></div>
							<div class="stopFloat"></div>
						</div>
						<div id="ecocalculateur_relation_result_chart_title_container">
							<span id="ecocalculateur_relation_result_chart_title1" class="ecocalculateur_relation_result_chart_title">Par UTI (<span id="ecocalculateur_relation_result_chart_title1_unit" class="unit"></span>)</span>
							<span id="ecocalculateur_relation_result_chart_title2" class="ecocalculateur_relation_result_chart_title">Global (<span id="ecocalculateur_relation_result_chart_title2_unit" class="unit"></span>)</span>
							<div class="stopFloat"></div>
						</div>
						<div id="ecocalculateur_relation_result_chart_legend_container">
							<div id="ecocalculateur_indicateur_energie" class="selected"></div>
							<div id="ecocalculateur_indicateur_co2" class="unselected"></div>
							<div id="ecocalculateur_relation_result_chart_legend"></div>
							<div class="stopFloat"></div>
						</div>
					</div>
					
					<div id="ecocalculateur_relation_result_text">
						<div id="ecocalculateur_relation_result_text_top">
							Cette relation représente<br/>
							<strong>un gain de</strong><br/>
							<span id="ecocalculateur_relation_result_text_unit">unité</span>
							<div id="ecocalculateur_relation_result_text_gap_container"></div>
							<div class="stopFloat"></div>
							<span id="ecocalculateur_relation_result_text_scenario">par rapport à un scénario routier</span>
						</div>
						<div id="ecocalculateur_relation_result_text_bottom">
							<div id="ecocalculateur_relation_result_text_arrow"></div>
							<div id="ecocalculateur_relation_result_text_clear_input" class="ecocalculateur_link">Réinitialisation</div>
							<div id="ecocalculateur_relation_result_text_add_relation" class="ecocalculateur_link">Ajouter une relation</div>
						</div>
					</div>
					<div class="ecocalculateur_relation_abstract">
						<table>
							<tr id="ecocalculateur_relation_abstract_container">
							</tr>
						</table>
					</div>
					
					<div id="ecocalculateur_footer_button_container">
						<div id="ecocalculateur_print_button">Imprimer</div>
						<div id="ecocalculateur_pdf_button">Télécharger</div>
						<div id="ecocalculateur_pdf_guide_methodologique_button"><a href="/medias/files/Guide_methodologique_ecocalculateur.pdf">Guide Méthodologique</a></div>
						<div class="stopFloat"></div>
					</div>
					
				</div>
				<div id="ecocalculateur_global_tab">
						<div id="ecocalculateur_global_title">
							<span id="ecocalculateur_global_title_1">ÉCO<span class="sub">2</span>Calculez</span><br/>
							<span id="ecocalculateur_global_title_2">Votre gain de CO<span class="sub">2</span>
                                                        <span id="ecocalculateur_global_title_3">
                                                            Naviland Cargo, c’est un gain moyen de 20% d’empreinte C02.<br/> 
                                                            Renseignez le formulaire ci-contre pour préciser une (des) relation(s).
                                                        </span>
						</div>
					<div id="ecocalculateur_global_left_container">
						
						<div id="ecocalculateur_global_result_text">
							L'ensemble de ces relations en<br/>
							<strong>Combiné</strong> Rail-route représente<br/>
							<strong>un gain</strong> de<br/>
							<strong id="ecocalculateur_global_result_text_unit">unité</strong>
							<div id="ecocalculateur_global_result_text_gap_container">
							</div>
							<div class="stopFloat"></div>
							<span id="ecocalculateur_global_result_text_scenario">par rapport à un scénario routier</span>
						</div>
					</div>
					
					<div id="ecocalculateur_global_charts_container">
						<div id="ecocalculateur_global_chart_kpi_container" class="ecocalculateur_global_chart"></div>
						<div id="ecocalculateur_global_chart_global_container" class="ecocalculateur_global_chart"></div>
						<div class="stopFloat"></div>
						<div class="ecocalculateur_global_chart_title">Par UTI (<span id="ecocalculateur_global_chart_kpi_unit" class="unit"></span>)</div>
						<div class="ecocalculateur_global_chart_title">Global (<span id="ecocalculateur_global_chart_global_unit" class="unit"></span>)</div>
						<div class="stopFloat"></div>
					</div>
					
					<div id="ecocalculateur_global_right_container">
						<div id="ecocalculateur_global_legende_container">
							<div id="ecocalculateur_global_indicateur_energie" class="selected"></div>
							<div id="ecocalculateur_global_indicateur_co2" class="unselected"></div>
							<div id="ecocalculateur_global_legende_image_container"></div>
						</div>
						
						<div id="ecocalculateur_global_arrow">
						</div>
						<div id="ecocalculateur_global_clear_input" class="ecocalculateur_link">Réinitialisation</div>
					</div>
					
					<div class="ecocalculateur_global_relation_abstract" id="ecocalculateur_global_relation_abstract_container">
					</div>
					
					<div id="ecocalculateur_global_footer_button_container">
						<div id="ecocalculateur_global_print_button">Imprimer</div>
						<div id="ecocalculateur_global_pdf_button">Télécharger</div>
						<div class="stopFloat"></div>
					</div>
					
					<div class="stopFloat"></div>
					
				</div>
			</div>
			<div class="stopFloat"></div>
		</div>
		
		<!-- Popup itinéraire impossible -->
		<div id="ecocalculateur_popup_error_route" title="Message">
			<p>L'itinéraire sélectionné n'existe pas.</p>
		</div>
		
		<!-- Popup probleme communication avec EcoTransIT-World -->
		<div id="ecocalculateur_popup_error_wsclienv" title="Message">
			<p>Les données saisies ne permettent pas de calculer les impacts environnementaux de la relation.</p>
		</div>
		
		<!-- Textes -->
		<input type="hidden" id="ecocalculateur_text_chart_road_popup_title" value="Scénario routier"/>
		<input type="hidden" id="ecocalculateur_text_chart_naviland_prepost_popup_title" value="NAVILAND - Route"/>
		<input type="hidden" id="ecocalculateur_text_chart_naviland_main_popup_title" value="NAVILAND - Fer"/>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){$('div#core .image_layer').css('background', 'transparent url(/medias/images/bg/<?php echo $this->controller . "_" . $this->action ?>.jpg) no-repeat 0 center');});
</script>