
<?php if ($this->lists) { ?>

<table id="daigouTable">
    
    <tr>
        <th>产品名字</th>
        <th>图片</th>
        <th>品牌</th>
        <th>链接</th>
        <th>大概价格</th>
        <th>数量</th>
        <th>购买人</th>
        <th>状态</th>
        <th>创建时间</th>
    </tr>
    
    <?php foreach ($this->lists as $row) { ?>
    <tr>
        <td><?php echo $row['name'] ?></td>
        <td><?php echo $row['has_img'] ?></td>
        <td><?php echo $row['brand'] ?></td>
        <td><?php echo $row['url'] ?></td>
        <td><?php echo $row['unit_price'] ?></td>
        <td><?php echo $row['quantity'] ?></td>
        <td><?php echo $row['buyer'] ?></td>
        <td><?php echo $row['status'] ?></td>
        <td><?php echo $row['create_ts'] ?></td>
    </tr>
    <?php } ?>
    
    </table>
<?php } ?>
