<!doctype html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>DiLin大头</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/public/images/dee-2010-04.jpg">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/layout.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/jquery-ui.css" />
    <script type="text/javascript">
        var baseUrl = '<?php echo $this->baseUrl(); ?>';
    </script>
    <script src="<?php echo $this->baseUrl() ?>/public/js/jquery-1.9.1.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/public/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/script.js"></script>
      
</head>

<body>
    <div id="body-wrapper">
        
        <!-- start header -->
        <div id="header">
            <div id="header-wrapper">
                <div id="header-title">DI LIN</div>
                <div id="header-menu">
                    <ul style="margin: 0 auto;">
                        <li><a href="">HOME</a></li>
                        <li><a href="">PHOTOS</a></li>
                        <li><a href="">SALES</a></li>
                        <li><a href="">ACTIVITIES</a></li>
                        <li><a href="">CONTACT</a></li>
                    </ul>
                </div>
            </div> 
            <div id="navigation">
                    <ul>
                        <li <?php if ($this->indexSelected) { ?> class="active" <?php } ?>><a href="/">HOME</a></li>
                        <li <?php if ($this->blogsSelected) { ?> class="active" <?php } ?>><a href="/blogs">BLOG</a></li>
                        <li <?php if ($this->salesSelected) { ?> class="active" <?php } ?>><a href="/sales">SALES</a></li>
                        <li <?php if ($this->photosSelected) { ?> class="active" <?php } ?>><a href="/photos">PHOTOS</a></li>
                        <li <?php if ($this->projectsSelected) { ?> class="active" <?php } ?>><a href="/projects">PROJECTS</a></li>
                        <li <?php if ($this->contactSelected) { ?> class="active" <?php } ?>><a href="/contact">CONTACT ME</a></li>
                </ul>
            </div>
        </div>
        <!-- end header -->
        
        
        <!-- start main -->
        <div id="main">
            <div id="main-wrapper">
            <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <!-- end main -->
        
        
        
    </div>
    
</body>
</html>
