<!doctype html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>DiLin大头</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/public/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/jquery-ui.css" />
    <script type="text/javascript">
        var baseUrl = '<?php echo $this->baseUrl(); ?>';
    </script>
    <script src="<?php echo $this->baseUrl() ?>/public/js/jquery-1.9.1.min.js"></script>
   
</head>
<body>
    This site will be up shortly.
    <script src="<?php echo $this->baseUrl(); ?>/public/js/plugins.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/public/js/script.js"></script>
</body>
</html>
