<!doctype html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>DiLin大头</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/layout.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/jquery-ui.css" />
    <script type="text/javascript">
        var baseUrl = '<?php echo $this->baseUrl(); ?>';
    </script>
    <script src="<?php echo $this->baseUrl() ?>/public/js/jquery-1.9.1.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/public/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/script.js"></script>
      
</head>

<body>
    <div id="body-wrapper">
        
        <!-- start header -->
        <div id="header">
            <div id="header-wrapper">
                <div id="header-title">DI LIN</div>
                <div id="header-menu">
                    <ul>
                        <li><a href="">HOME</a></li>
                        <li><a href="">BLOG</a></li>
                        <li><a href="">SALES</a></li>
                        <li><a href="">PHOTOS</a></li>
                        <li><a href="">CONTACT</a></li>
                    </ul>
                </div>
	        
            </div> 
            <div id="breadcrumbs">
                <div id="breadcrumbs-wrapper">
                    <a href="/">HOME</a>
                    
                    <?php if (isset($this->controller)) { ?>
                        > <?php echo $this->controller ?>
                    <?php } ?>
                </div>
            </div>
        </div>
        <!-- end header -->
        
        
        <!-- start main -->
        <div id="main">
            <div id="main-wrapper">
            <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <!-- end main -->
        
        
        
    </div>
    
</body>
</html>
